#!/usr/bin/env bash
#This bash script displays the PID,
#along with the process name,
#of process whose name contain the word bash

for pid in /proc/[0-9]*; do
	name=$(cat "$pid/comm" 2>/dev/null)
	pid=$(basename "$pid")
	if [[ "$name" == $"bash"* ]]; then
		echo "$pid $name"
	fi
done

