#!/usr/bin/env bash
#this bash script  stopped our 4-to_infinity_and_beyond 
#process using ctrl+c in the previous task

file_name="4-to_infinity_and_beyond"
pids=$(pgrep -f "$file_name")
if [ -n "$pids" ]; then
  kill "$pids"
fi
