#!/usr/bin/env bash
#this Bash script that displays:
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

trap 'echo "T am invincible!!!"' SIGTERM
while :
do
	echo "To infinity and beyong"
	sleep 2
done
