#!/usr/bin/env bash
#This Bash script  displays numbers from 1 to 100.
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number

i=1
while [ $i -lt 101 ]; do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -ne 0 ]; then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -ne 0 ]; then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
		echo "FizzBuzz"
	else
		echo "$i"
	fi
	((i++))
done
