#!/usr/bin/env bash
#This bash script displaying "Best School" 10 times using while loop.
#on the 9th iterations, displaing "Hi" before "Best School".

cnt=0

while [ $cnt -lt 10 ]
do
    if [ $cnt -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    (( cnt++ ))
done
