#!/usr/bin/env bash
#This bash script displaying "Best School" for other iterations using while loop.
#on the 4th iterations, displaing "bad luck" before "Best School".
#on the 8th iterations, displaing "good luck" before "Best School".

i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
