#!/usr/bin/env bash
#This bash script displaying "Best School" for other iterations using while loop.
#on the 4th iterations, displaing "bad luck" before "Best School".
#on the 8th iterations, displaing "good luck" before "Best School".

cnt=0

while [ $cnt -lt 10 ];
do
    if [ $cnt -eq 3 ];
    then
        echo "bad luck"
    elif [ $cnt -eq 7 ];
    then
        echo "good luk"
    else
        echo "Best School"
    fi
    (( cnt++ ))
done
