#!/usr/bin/env bash
# This bash script displaying nombers from 1 to 20 in addition to:
#"bad luck in China" for the 4th loop iteration.
#"bad luck from Japan" for the 9th  loop iteration.
#"bad luck from Italy" for the 17th  loop iteration.

cnt=1

while [ $nt -lt 20 ]
do
    echo "$cnt"
    case $cnt in
        "4")echo "bad luck from China";;
        "9")echo "bad luck from Japan";;
        "17")echo "bad luck from Italy";;
    esac
    (( cnt++ ))
done
