#!/usr/bin/env bash
#This bash script displaying the time for 12 hours and 59 minutes.
#displaing hours from 0 to 12
#displaing minutes from 1 to 59

hr=0
while [ $hr -lt 12 ]
do
    echo "Hour: $hr"
    mnt=1
    while [ $mnt -lt 59 ]
    do
        echo "$mnt"
        (( mnt++ ))
    done
    (( hr++ ))
done
