#!/usr/bin/env bash
#This bash script displaying the content of the current directory in list format.
#only display the path of the name after yhr first dash.

list=$(ls)
for i in $list; do
    echo "$i" | cut -d '_' -f2
done
