#!/usr/bin/env bash
#This bash script displaying the content of the current directory in list format.
#only display the path of the name after yhr first dash.

for file in *;
do
    if [ "$file" ]; then
        echo "${file#*-}"
    fi
done
